@startuml
title X(Twitter) - User Interaction Flow


|User Interface|
start
:Launch X-Twitter Application;
if (User Authenticated?) then (no)
  :Display Login Screen;
  :Enter Credentials;
  |Authentication Service|
  :Validate Credentials;
  if (Credentials Valid?) then (yes)
    |User Interface|
    :Load User Dashboard;
  else (no)
    :Show Authentication Error\n  Back to "Login Screen";
    stop
  endif
else (yes)
  |User Interface|
  :Load User Dashboard;
endif

|User Interface|
:View Timeline;
fork
  :Compose Tweet;
  |Tweet Service|
  :Validate Tweet Content;
  if (Content Meets Guidelines?) then (yes)
    :Process New Tweet;
  else (no)
    :    Show Content Error\nBack to "Compose Tweet";
    stop
  endif
fork again
  :Like Tweet;
  |Engagement Service|
  :Process Like;
fork again
  :Retweet;
  |Engagement Service|
  :Process Retweet;
fork again
  :Reply to Tweet;
  |Tweet Service|
  :Validate Reply Content;
  if (Content Meets Guidelines\n         and Policies?) then (yes)
    :Process Reply;
  else (no)
    : Show Content Error\nBck to "reply to tweet";
    stop
  endif
fork again
  :Mention User;
  |Notification Service|
  :Engagement Processing;
end fork

|Distributed Services|
:Update Engagement Metrics;
:Distribute to Followers;
:Update User Timeline;
:Generate Notifications;

|User Interface|
:Refresh Timeline;
:Display Updated Content;

stop
@enduml